USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FIVETRAN_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE ORDERS (
  ORDER_ID NUMBER,
  ORDER_DATE VARCHAR,
  CUSTOMER_ID VARCHAR,
  CUSTOMER_NAME VARCHAR,
  CATEGORY VARCHAR,
  PRODUCT VARCHAR,
  QUANTITY NUMBER,
  UNIT_PRICE NUMBER(10, 2),
  STATUS VARCHAR
);
