USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FIVETRAN_DB;
USE SCHEMA RAW;

COPY INTO ORDERS
  FROM @%ORDERS
  FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
  )
  ON_ERROR = 'CONTINUE';

SELECT COUNT(*) AS RAW_ROW_COUNT FROM ORDERS;
