-- Run after dbt has written MARTS.
-- Ticket: "I can query the transformed data in Snowflake and generate simple reports."

USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;

-- Total sales by category
SELECT
  CATEGORY,
  ORDER_COUNT,
  TOTAL_SALES
FROM MARTS.SALES_BY_CATEGORY
ORDER BY TOTAL_SALES DESC;

-- Orders per customer
SELECT
  CUSTOMER_ID,
  CUSTOMER_NAME,
  ORDER_COUNT,
  TOTAL_SALES
FROM MARTS.ORDERS_PER_CUSTOMER
ORDER BY TOTAL_SALES DESC
LIMIT 10;

-- Monthly trend
SELECT
  ORDER_MONTH,
  ORDER_COUNT,
  TOTAL_SALES
FROM MARTS.SALES_TREND
ORDER BY ORDER_MONTH;
